apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: animal-api
  template:
    metadata:
      labels:
        app: animal-api
    spec:
      containers:
      - name: animal-api
        image: animal-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
