apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productapi
  template:
    metadata:
      labels:
        app: productapi
    spec:
      containers:
      - name: productapi
        image: productapi:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: 'http://+:80'