apiVersion: v1
kind: Service
metadata:
  name: productapi-service
spec:
  selector:
    app: productapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31509
  type: NodePort
